
/////////////////////////////////////////////////
// Automatically generated by xml2mockpp v1.16.4.
// xml2mockpp is part of Mock Objects for C++.
// See also http://mockpp.sourceforge.net
//
// Intended for manual and persistent changes 
/////////////////////////////////////////////////

#include "MockppIdlTest_mock.h"

